pipeline { 
    agent none

    stages{ 
        stage('build'){ 
            when {
                changeset "**/vote/**"
            }

            agent{
                docker{
                    image 'python:3.11-slim'
                    args '--user root'
                }
            }

            steps{ 
                echo 'Compiling vote app.' 
                dir('vote'){
                    sh "pip install -r requirements.txt"
                } 
            }
        } 
        stage('test'){
            when {
                changeset "**/vote/**"
            }

            agent {
                docker{
                    image 'python:3.11-slim'
                    args '--user root'
                }
            }
            steps{
                echo 'Running Unit Tests on vote app.' 
                dir('vote'){
                    sh "pip install -r requirements.txt"
                    sh 'nosetests -v'
                } 
            }
        }

        stage('docker-image') {
            agent any

            when {
                changeset "**/vote/**"
            }

            steps {
                echo 'Building and pushing docker image'

                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'mydockerlogin') {
                        def img = docker.build(
                            'breizhell/lfs-vote:latest',
                            './vote'
                        )

                        img.push('latest')
                    }
                }
            }
        }
    }

    post {
        always{
            echo 'Pipeline for vote is complete'
        }
    }

} 


