pipeline {
    agent {
        docker {
            image 'maven:3.9.8-sapmachine-21'
            args '-v $HOME/.m2:/root/.m2'
        }
    }
    

    stages{
        stage("build"){
            when {
                changeset "**/worker/**"
            }

            steps{
                echo 'Building worker app' 

                dir('worker'){
                    sh 'mvn compile'
                }
            }
        }

        stage("test"){ 
            when {
                changeset "**/worker/**"
            }

            steps{
                echo 'Running Unit Tests on worker app'

                dir('worker') {
                    sh 'mvn clean test'
                }
            }
        }

        stage("package"){
            when {
                changeset "**/worker/**"
            }

            steps{
                echo 'Packaging worker app into a .jar'

                dir('worker') {
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }

        stage('docker-image') {
            when {
                changeset "**/worker/**"
            }

            steps {
                echo 'Building and pushing docker image'

                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'mydockerlogin') {
                        def img = docker.build(
                            'breizhell/lfs-worker:v${env.BUILD_ID}',
                            './worker'
                        )

                        img.push('latest')
                    }
                }
            }
        }
    }

    post{
        always{
            echo 'Building multibranch pipeline for worker is completed..' 
        }
    }
}